# Introduction

A management strategy evaluation (MSE) is a structured decision-making process that evaluates the performance of alternative management actions in light of prespecified objectives. MSEs use simulation testing to evaluate the performance of potential management approaches in the face of uncertainty about current and future conditions. MSEs offer a flexible framework that can be used in support of diverse management needs, such as choosing a harvest control rule (e.g., Cox and Kronlund 2016), evaluating the long-term consequences of decisions about the structure of a stock assessment model (e.g., Wiedenmann et al. 2017), or the frequency of observation and assessment of a population (e.g., Hutniczak et al. 2019).

The degree of engagement with managers and stakeholders varies across MSE applications. Some exercises focus extensively on the simulation modeling component. For example, identifying the strengths and weaknesses of general types of assessment models or harvest control rules may be done without much outside input. MSE processes that are more linked to decision-making often benefit from broad stakeholder input. A manager- and stakeholder-driven MSE also creates an opportunity for adopting a transdisciplinary research model and promotes resource comanagement. Transdisciplinary research integrates knowledge from scientific and societal bodies of knowledge, creating opportunities for mutual learning, and coproducing solution-oriented knowledge (Lang et al. 2012).

Most simulation testing frameworks used in MSEs share similar elements (Figure 1). They typically involve simulation models of an underlying population or biological system of interest (operating model), how it is observed and quantified by people (observation model and estimation model), and how decisions are made with respect to its management (management model).
